[tox]
envlist = py,ruff
minversion = 4.0
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
extras = test
commands = pytest {posargs} tests

[testenv:ruff]
runner = uv-venv-lock-runner
extras = ruff
commands =
    ruff check tests
    ruff format --check tests

[testenv:develop]
runner = uv-venv-lock-runner
extras = test,ruff
